begin;

-- Extend the profile role check without changing any existing account role.
alter table public.users
  drop constraint if exists users_role_check;

alter table public.users
  add constraint users_role_check
  check (role = any (array['crew'::character varying, 'manager'::character varying, 'finance'::character varying]));

-- Base hourly pay and tier duration thresholds. Thresholds count completed,
-- scheduled attendance days; the application advances the tier after checkout.
create table if not exists public.payroll_tier_rates (
  tier text primary key check (tier in ('pra_training', 'training', 'junior', 'senior')),
  hourly_rate numeric(12,2) not null check (hourly_rate >= 0),
  work_days_to_next_tier integer check (work_days_to_next_tier is null or work_days_to_next_tier > 0),
  updated_at timestamptz not null default now()
);

insert into public.payroll_tier_rates (tier, hourly_rate, work_days_to_next_tier)
values
  ('pra_training', 5000, 3),
  ('training', 5000, 22),
  ('junior', 6000, 24),
  ('senior', 6800, null)
on conflict (tier) do update
set hourly_rate = excluded.hourly_rate,
    work_days_to_next_tier = excluded.work_days_to_next_tier,
    updated_at = now();

create table if not exists public.payroll_senior_plus_rates (
  level smallint primary key check (level between 1 and 5),
  daily_bonus numeric(12,2) not null check (daily_bonus >= 0),
  updated_at timestamptz not null default now()
);

insert into public.payroll_senior_plus_rates (level, daily_bonus)
values (1, 5000), (2, 7500), (3, 12000), (4, 20000), (5, 26000)
on conflict (level) do update
set daily_bonus = excluded.daily_bonus,
    updated_at = now();

-- One current tier record per crew account. Existing crew are deliberately
-- not initialized here: their current tier and days-in-tier must be entered
-- from verified operational data instead of being guessed.
create table if not exists public.crew_payroll_status (
  user_id uuid primary key references public.users(id) on delete restrict,
  tier text not null default 'pra_training'
    references public.payroll_tier_rates(tier) on update cascade on delete restrict,
  completed_days_in_tier integer not null default 0 check (completed_days_in_tier >= 0),
  senior_plus_level smallint not null default 0 check (senior_plus_level between 0 and 5),
  updated_by uuid references public.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  check (tier = 'senior' or senior_plus_level = 0)
);

create or replace function public.initialize_crew_payroll_status()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.role = 'crew' then
    insert into public.crew_payroll_status (user_id, tier, completed_days_in_tier)
    values (new.id, 'pra_training', 0)
    on conflict (user_id) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists users_initialize_crew_payroll_status on public.users;
create trigger users_initialize_crew_payroll_status
after insert on public.users
for each row execute function public.initialize_crew_payroll_status();

-- Payroll runs and per-crew snapshots keep exported/finalized totals auditable.
create table if not exists public.payroll_periods (
  id bigint generated by default as identity primary key,
  period_start date not null,
  period_end date not null,
  status text not null default 'draft' check (status in ('draft', 'finalized')),
  created_by uuid not null references public.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  finalized_at timestamptz,
  check (period_end >= period_start),
  unique (period_start, period_end)
);

create table if not exists public.payroll_items (
  id bigint generated by default as identity primary key,
  payroll_period_id bigint not null references public.payroll_periods(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete restrict,
  scheduled_hours numeric(8,2) not null default 0 check (scheduled_hours >= 0),
  completed_work_days integer not null default 0 check (completed_work_days >= 0),
  base_pay numeric(12,2) not null default 0 check (base_pay >= 0),
  senior_plus_pay numeric(12,2) not null default 0 check (senior_plus_pay >= 0),
  deductions numeric(12,2) not null default 0 check (deductions >= 0),
  net_pay numeric(12,2) not null default 0 check (net_pay >= 0),
  calculation_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (payroll_period_id, user_id)
);

create table if not exists public.payroll_adjustments (
  id bigint generated by default as identity primary key,
  payroll_period_id bigint not null references public.payroll_periods(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete restrict,
  adjustment_type text not null check (adjustment_type in ('sp_deduction', 'other_deduction', 'addition')),
  amount numeric(12,2) not null check (amount > 0),
  reason text not null check (length(trim(reason)) > 0),
  attendance_id integer references public.attendance(id) on delete set null,
  recorded_by uuid not null references public.users(id) on delete restrict,
  created_at timestamptz not null default now()
);

create index if not exists payroll_items_user_idx on public.payroll_items (user_id);
create index if not exists payroll_adjustments_period_user_idx
  on public.payroll_adjustments (payroll_period_id, user_id);

-- Finance-only access to rates, payroll runs, snapshots, and adjustments.
alter table public.payroll_tier_rates enable row level security;
alter table public.payroll_senior_plus_rates enable row level security;
alter table public.crew_payroll_status enable row level security;
alter table public.payroll_periods enable row level security;
alter table public.payroll_items enable row level security;
alter table public.payroll_adjustments enable row level security;

grant select on public.payroll_tier_rates, public.payroll_senior_plus_rates to authenticated;
grant select, insert, update, delete on public.crew_payroll_status to authenticated;
grant select, insert, update, delete on public.payroll_periods to authenticated;
grant select, insert, update, delete on public.payroll_items to authenticated;
grant select, insert, update, delete on public.payroll_adjustments to authenticated;
grant usage, select on sequence
  public.payroll_periods_id_seq,
  public.payroll_items_id_seq,
  public.payroll_adjustments_id_seq
to authenticated;

drop policy if exists "Finance can read tier rates" on public.payroll_tier_rates;
create policy "Finance can read tier rates"
  on public.payroll_tier_rates for select to authenticated
  using (exists (select 1 from public.users u where u.id = auth.uid() and u.role = 'finance'));

drop policy if exists "Finance can read senior plus rates" on public.payroll_senior_plus_rates;
create policy "Finance can read senior plus rates"
  on public.payroll_senior_plus_rates for select to authenticated
  using (exists (select 1 from public.users u where u.id = auth.uid() and u.role = 'finance'));

drop policy if exists "Crew can read own payroll tier and finance can manage all" on public.crew_payroll_status;
create policy "Crew can read own payroll tier and finance can manage all"
  on public.crew_payroll_status for select to authenticated
  using (
    user_id = auth.uid()
    or exists (select 1 from public.users u where u.id = auth.uid() and u.role = 'finance')
  );

drop policy if exists "Finance can manage crew payroll status" on public.crew_payroll_status;
create policy "Finance can manage crew payroll status"
  on public.crew_payroll_status for all to authenticated
  using (exists (select 1 from public.users u where u.id = auth.uid() and u.role = 'finance'))
  with check (exists (select 1 from public.users u where u.id = auth.uid() and u.role = 'finance'));

drop policy if exists "Finance can manage payroll periods" on public.payroll_periods;
create policy "Finance can manage payroll periods"
  on public.payroll_periods for all to authenticated
  using (exists (select 1 from public.users u where u.id = auth.uid() and u.role = 'finance'))
  with check (exists (select 1 from public.users u where u.id = auth.uid() and u.role = 'finance'));

drop policy if exists "Finance can manage payroll items" on public.payroll_items;
create policy "Finance can manage payroll items"
  on public.payroll_items for all to authenticated
  using (exists (select 1 from public.users u where u.id = auth.uid() and u.role = 'finance'))
  with check (exists (select 1 from public.users u where u.id = auth.uid() and u.role = 'finance'));

drop policy if exists "Finance can manage payroll adjustments" on public.payroll_adjustments;
create policy "Finance can manage payroll adjustments"
  on public.payroll_adjustments for all to authenticated
  using (exists (select 1 from public.users u where u.id = auth.uid() and u.role = 'finance'))
  with check (exists (select 1 from public.users u where u.id = auth.uid() and u.role = 'finance'));

commit;
