create table if not exists public.schedule_jobdesk_block (
  id bigint generated by default as identity primary key,
  schedule_id bigint not null references public.schedule(id) on delete cascade,
  jobdesk_id bigint not null references public.jobdesk(id) on delete cascade,
  mulai_menit integer not null check (mulai_menit >= 0 and mulai_menit < 2880),
  selesai_menit integer not null check (selesai_menit > mulai_menit and selesai_menit <= 2880),
  created_at timestamptz not null default now(),
  unique (schedule_id, jobdesk_id, mulai_menit, selesai_menit)
);

create index if not exists schedule_jobdesk_block_schedule_idx
  on public.schedule_jobdesk_block (schedule_id, mulai_menit, selesai_menit);

alter table public.schedule_jobdesk_block enable row level security;

create policy "Managers can manage schedule jobdesk blocks"
  on public.schedule_jobdesk_block
  for all
  to authenticated
  using (
    exists (
      select 1 from public.users
      where users.id = auth.uid() and users.role = 'manager'
    )
  )
  with check (
    exists (
      select 1 from public.users
      where users.id = auth.uid() and users.role = 'manager'
    )
  );

create policy "Crew and managers can read schedule jobdesk blocks"
  on public.schedule_jobdesk_block
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.users
      where users.id = auth.uid() and users.role = 'manager'
    )
    or exists (
      select 1
      from public.schedule s
      where s.id = schedule_jobdesk_block.schedule_id
        and s.user_id = auth.uid()
    )
  );
